### ISSUE TITLE
correct definition of includes()

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/dusty-codes-site#22]
The word "at" is repeated and one should be removed.

Also, in the **Arguments** section, the type of `list` should be `array` or `string`.

![screen shot 2018-10-02 at 11 37 07 pm](https://user-images.githubusercontent.com/23492367/46388796-551d9500-c69c-11e8-9948-2f10222de847.png)

**Comment by dhershman1** [comment]
This has been addressed as well as the bad math on the compose function. Fixed with release v0.9.2 of kyanite.
